Remove deleted organization from configuration file
The "snowfox-project" GitHub organization has been deleted. This caused the script runs to fail:

```
fastcore.net.HTTP404NotFoundError: HTTP Error 404: Not Found
====Error Body====
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest",
  "status": "404"
}
```